name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Check format
        run: test -z "$(gofmt -l .)"

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -v

      - name: Build client
        run: go build ./cmd/lar

      - name: Build gateway
        run: go build ./cmd/lar-gateway
